### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/ccompass#1]
How would you feel adding effective but expensive waypoint poles? The recipe could be sticks and mese crystals. The way waypoints would be displayed could be similar to how [gps](https://github.com/BrunoMine/gps) displays its waypoints.

**Comment by bell07** [comment]
Interesting Idea.

Basically I do not have the issue to define the different "pole" but at the time I do not see an intuitive way to assign a waypoint to a compass. Du you have any idea? If you get the waypoint sticks and place them to the world, how you like to calibrate a compass to use them?

My Idea at the time is to wait till 0.4.16 is released. The next version allow to override the item description in inventory, so I can add an information "Compass to x,y,z" or "Compass - Punch to calibrate to this point" or something like directly to the item description. In case of Waypoints it can be "Compass to waypoint xyz", instead of persistent visible HUD. The utilization of item description  has the advantage you can free rename it (like to "my home") using the engrave mod https://forum.minetest.net/viewtopic.php?f=11&t=17482

**Comment by tacotexmex** [comment]
I would think that right-clicking with a compass on a placed pole would intuitively provide a way to calibrate the compass. (The mese fragment in the compass "magnetizes" with the mese in the pole)

**Comment by bell07** [comment]
I am thinking to calibrate by right-clicking on each point without special pole waypoints. But as mentioned above not yet, but if I can change the item description in calibration.

Mostly I craft a compass to find a way (again) to a specific point like  to the home because I start my explorations without them (unplanned gets lost the way). So local calibration is mostly useless for me :-(. Do you see a simple way for remote calibration? I do not like to add a formspec to the compass because it feels strange for me to use an user-interface on old-fashioned compass :-/

**Comment by tacotexmex** [comment]
I realize by naming it "waypoints" it probably sounds like I want a series of coordinates to be internally linked, since that is what the word really means. In the gps mod however, a waypoint is just a single xyz coordinate. So my idea is a little easier than what it sounded like.

I think that if you don't want a pole to be crafted, it could still be placed on top of a node when rightclicking it with the compass. Kind of like: ⛳️ .

I do find the concept of "real" waypoints interesting however. Imagine a compass holding a multi-coordinate path to secrets and treasures, that can be given to other players.

**Comment by bell07** [comment]
I did understand you right ;-) To set the target by rightclicking is technically not the issue. I can implement it as compass_mode="on_use". I do not like to implement the ⛳️ just for the reason I cannot paint them :(. But it would be just decoration and not really needed technically. You can rightclicking the compass just on the stone ahead the door to a hidden temple or so...
In had already the idea to take a treasurer mod: place chests with compass that already calibrated to other chest, (German Schnitzeljagd). ;-)
Other idea: give is a "Home-Compass" to other player for invitation. I think the "origin" mode (= target stored in compass meta)  will be the main mode at the next time...

**Comment by tacotexmex** [comment]
Oh, good.
I fully realize that technically a pole is not needed at all, but conceptually I find it confusing that a compass would magically be calibrated to stone or dirt. Even in MT worlds, some game mechanic logic is appreciated I think as it helps immersion. There's also an interesting mechanic if you could lose your waypoint by someone else digging the pole, but that's not necessary.

I'll draw the pole for you.

That treasure idea sounds good as well (Swedish: snitseljakt). On that note, check out [Polaris](https://forum.minetest.net/viewtopic.php?id=8256) mod for ideas.

**Comment by bell07** [comment]
Ok, conceptually you are right, it should help to avoid "misstake-recalibration" by punch.
Maybe you paint 2 different pole-flags? Using the first one the player could mark his home. All not calibrated compass should point to them till (like currently to "home" or "bed").
The second type is for calibration as proposed.
The lose the waypoint on digging pole is technically difficult, I do not like to track all compasses, so I cannot update them all. The compass could be in a "prestibag" in a chest in an unloaded area so I cannot scan the whole map to update all compass maybe point to this coordinates. The other direction, to poll the target for changes, is not really nice too.

**Comment by tacotexmex** [comment]
Okay, cool. I could draw two, but haven't you already made settingtypes for that behavior?

I would suggest a priority of needle direction as such (the latter overrides the former):
1. Completely uncalibrated compass needle points north, the needle set to color X.
2. If a player has an updated spawn point, the needle changes to color Y and points there.
3. If a pole is placed and associated with the compass, the needle changes to color Z and points there. Also adding a visible waypoint on screen (preferrably with an unique name of the pole)

A bigger featureset than above would start to confuse things I think.

I can see why you don't want an all-world compass tracker in there. I'm definitively not a coder, but couldn't the data be stored in the database? I read that somewhere, but I'm noobish when it comes to that.

**Comment by bell07** [comment]
I think I let the implemented compass_mode untouched and implement the new one "calibrate". Both poles are for this new mode and only in this new mode available.
I cannot change the colour of the needle, so the compass will be always visible as is. Therefore I like to manipulate the Item description (again, 0.4.16. If I find time before, I can temporary use HUD like in gps-mod for target info).
In the first step 1. and 2. are the same compass behaviour, like before in other modes. I cannot decide if the "bed", "sethome" or "static_spawnpoint" is the "updated spawn point". Therefore the idea about a new own one (compass:pole_flag_home?) If this one does not exists the compass points to 0,0,0
For Step 3: I plan to ask for a point name (small formspec) after placing the pole. If name is set the compass will be renamed to "Compass to pointname" in calibration.

About databases: The whole MT-map is a database ;) But this database is designed to be usually loaded incomplete because of "nearly infinite world". I try to avoid an additional table in database that needs to be always loaded and should contain whereabouts of either all poles or all compasses in the world, without loosing them on reboot or technically crashes.

**Comment by bell07** [comment]
Hm, the idea for flags/pole-nodes feels still wrong /not generic enough for me for two reasons:
1. No matter how beautiful the pole is, it cannot match to all environments you need to mark up. A "Flag" will be strange in a ancient temple for example. In other words the idea is not generic enough for me to be usefill in all cases and subgames the compass can be.
2. If you find any interesting you need to mark, you do not have usual the items to craft the expensive pole.

But I can add a setting "Calibration nodes" to the mod, (default is all nodes) and you can create own mod with "compass-poles", and set the setting for it (or just use mese-bloock if you like). That is generic enough to define the poles fitting to each subgame, if needed. The setting is generic enough for the next idea: not-craftable poles placed in map generation (like the temple mod can generate a compass-pole each temple for example). Could be interessting too, but maybe other mod, keeping this mod KiSS ;)

**Comment by tacotexmex** [comment]
Yes, your way of outsorcing this to another possible mod sounds like the best way. Good thinking!

**Comment by tacotexmex** [comment]
Found something called waynode, but haven't had the chance to try it out yet. Might be of use for this project. https://github.com/Dragonop/waynode

**Comment by bell07** [comment]
I looked to the waynode code and tried it short. The mod seems to be unfinished and does not work right. Maybe I will fork it and take some changes, but I need to understand the goal of this mod at first. Which functionality should the waynode provide if used without compass?

**Comment by tacotexmex** [comment]
I'd figure some smart positioning method if it existed, or nothing, probably the latter. Like I said, I didn't have the chance to look at it properly, but I didn't want to miss a chance to reduce coding effort :)

**Comment by bell07** [comment]
I did a rework, now the mod is called "Calibrated compass", as described before now it is possible to calibrate each compass to each place. Specific nodes support is implemented too. See https://forum.minetest.net/viewtopic.php?f=9&t=17881
I removed all other compass modes because the new way I like much better and do not like to support the old ways. 
Anything missed? Or I can close this "issue"?

**Comment by tacotexmex** [comment]
Cool, I'll test it out and see!

**Comment by tacotexmex** [comment]
Yes! This works very simple and intuitive I got to say. Plus, the range of settings for server owners _and_ developers makes this one tweakable in all ways we've discussed as far as I can tell. Good work.

I feel like the textures could use an overhaul so perhaps I can find time to draw those, to even further increase the value of this mod.

**Comment by tacotexmex** [comment]
One small thing that's worth mentioning is that I originally suggested waypoints being displayed on-screen, much like name tags (and how [gps](https://github.com/BrunoMine/gps)). This also showed the vertical position.

Having those would sort of defeat the purpose of a compass needle however and may be out of the scope of a compass mod. Just thought it would be worth mentioning.

**Comment by bell07** [comment]
At the time I do not use the compass by self because of teleporters that transport me directly to the destination oO ..

I think it should not be too easy to find a place using the compass. I do not like additional HUD informations because it is "Terminator-like" and not "Human-like". But if any one provide pull requests with optional functionality I will merge them. Agree the "Y" value in coordinates is unused at the time. But I do not see the intuitive way for this at the time.
Your offer about new textures I gladly accept ;)
